### ISSUE TITLE
how to get "models_info.txt"

### ISSUE THREAD

**Issue by evan6007** [tjiiv-cprg/EPro-PnP#1]
When I run the test, it show file not found error.
so where can i get the models_info.

**Comment by Lakonik** [comment]
Hi! Thank you for your interest in our work!
Which model are you testing? Can you report the environment, command, and error message?

**Comment by evan6007** [comment]
Thank you for your reply
my env: ubuntu18.04 cuda11.3 pytorch1.10.1

when i use the the EPro-PnP-6DoF/tools/main.py
`python3 main.py --cfg ./exps_cfg/epropnp_basic.yaml`
show this:

> Traceback (most recent call last):
>   File "main.py", line 108, in <module>
>     main()
>   File "main.py", line 63, in main
>     LM(cfg, 'test'),
>   File "/home/evan/桌面/EPro-PnP/EPro-PnP-6DoF/tools/../lib/datasets/lm.py", line 30, in __init__
>     self.infos = self.load_lm_model_info(ref.lm_model_info_pth)
>   File "/home/evan/桌面/EPro-PnP/EPro-PnP-6DoF/tools/../lib/datasets/lm.py", line 144, in load_lm_model_info
>     with open(info_pth, 'r') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/evan/桌面/EPro-PnP/EPro-PnP-6DoF/lib/../dataset/lm/models/models_info.txt'

**Comment by Lakonik** [comment]
This file comes with the dataset. Please make sure that you prepared the dataset in the following structure. You probably put the data in the wrong path.
```
EPro-PnP-6DoF
├── dataset
│   ├── bg_images
│   │   └── VOC2012
│   └── lm
│       ├── models
│       │   ├── ape
│       │   └── ...
│       ├── imgn
│       │   ├── ape
│       │   └── ...
│       ├── real_test
│       │   ├── ape
│       │   └── ...
│       └── real_train
│           ├── ape
│           └── ...
```
